config/routes.rb
Rails.application.routes.draw do
  root 'application#launch'

  resources :certs, only: [:new, :create, :edit, :update]
  resources :tokencheck, only: [:show, :index]
  get 'tokencheck/index', to: "tokencheck#index"
  get 'tokencheck/check', to: "tokencheck#check"
  get 'application/launch_created', to: "application#launch_created"
  get 'application/redirect', to: "application#redirect"
  
  get 'certlist', to: "certlist#index"
  
  
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  # LTI XML CONFIG
  get :lti_config, controller: :application, as: :lti_config

  # LTI LAUNCH URL (responds to get and post)
  match 'launch' => 'application#launch', via: [:get, :post], as: :lti_launch
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tokencheck_controller.rb
class TokencheckController < ApplicationController
    def show
        @validation_token = params[:validation_token]
        user_emissions = Emission.where "validation_token like ?", "#{@validation_token}"

        if user_emissions.empty?
            @status = "danger"
            @message = "Código não encontrado!"
        else
            @status = "success"
            @message = "Código encontrado!"
            @emission = user_emissions.first
        end
    end
end

app/helpers/tokencheck_helper.rb
module TokencheckHelper
end

app/views/tokencheck/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h2 class="pt-4">Validar certificado</h2>
			<p>Você pode checar se o certificado é válido colocando o "Token do certificado" aqui e clicando em "validar".</p>
		</div>
	</div>
    
    <div class="row">
        <%= form_tag tokencheck_check_path, method: :get, class: "form-inline" do %>
            <div class="form-group mx-sm-3">
                <%= text_field_tag :validation_token, nil, class: "form-control", "aria-describedby" => "helpToken" %>
            </div>
            <%= button_to "Validar", @validation_token, class:"btn btn-primary" %>
        <% end %>
    </div>
</div>
    

app/views/tokencheck/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h2 class="pt-4">Validar certificado</h2>
			<p>Você pode checar se o certificado é válido colocando o "Token do certificado" aqui e clicando em "validar".</p>
		</div>
	</div>
    
    <div class="row">
        <%= form_tag tokencheck_check_path, method: :get, class: "form-inline" do %>
            <div class="form-group mx-sm-3">
                <%= text_field_tag :validation_token, @validation_token, class: "form-control", "aria-describedby" => "helpToken" %>
            </div>
            <%= button_to "Validar", @validation_token, class:"btn btn-primary" %>
        <% end %>
    </div>


    <div class="row mt-3">
        <div class="col-md-12">
            <div class="alert alert-<%= @status %>" role="alert">
                <%= @message %>
            </div>
        </div>
    </div>

    
    <% if !@emission.blank? %>
    <div class="row">
		<div class="col-md-12">
			<div class="iframe-holder">
				<iframe src="<%= rails_blob_url(@emission.certpdf) %>"> </iframe>
			</div>
		</div>
	</div>
    <% end %>
</div>