config/routes.rb
Rails.application.routes.draw do
  root 'application#launch'

  resources :certs, only: [:new, :create, :edit, :update]
  resources :tokencheck, only: [:show, :index]
  get 'tokencheck/index', to: "tokencheck#index"
  get 'tokencheck/check', to: "tokencheck#check"
  get 'application/launch_created', to: "application#launch_created"
  get 'application/redirect', to: "application#redirect"
  
  get 'certlist', to: "certlist#index"
  
  
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  # LTI XML CONFIG
  get :lti_config, controller: :application, as: :lti_config

  # LTI LAUNCH URL (responds to get and post)
  match 'launch' => 'application#launch', via: [:get, :post], as: :lti_launch
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# required for LTI
require 'ims/lti'
# Used to validate oauth signatures
require 'oauth/request_proxy/action_controller_request'
# Gerar token do certificado
require 'securerandom'



class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # CSRF stuff ^

  # LTI Launch endpoint (responds to POST and GET - see routes.rb)
  # checks for required query params
  # checks that the oauth signature checks out
  # read more about IMS::LTI in ims-lti gem https://github.com/instructure/ims-lti
  # note the oauth nonce is not handled within ims-lti gem, it's up to you
  def launch
    provider = IMS::LTI::ToolProvider.new(
      Rails.application.config.lti_settings['consumer_key'],
      Rails.application.config.lti_settings['consumer_secret'],
      request.query_parameters
    )

    if not provider.valid_request?(request)
      # the request wasnt validated :(
      render :launch_error, status: 401
      return
    end

    # The providre request is valid
    # store the values you need from the LTI
    # here we're just tossing them into the session
    session[:user_id] = params.require :user_id
    session[:context_id] = params.require :context_id
    session[:context_title] = params.require :context_title
    session[:lis_person_name_full] = params.require :lis_person_name_full
    session[:roles] = params.require :roles
    session[:resource_link_title] = params.require :resource_link_title
    
    #informações enviadas pelo canvas
    resource = session[:resource_link_title]
    context = session[:context_id]
    roles = session[:roles]
    user_id = session[:user_id]
    fullname = session[:lis_person_name_full]
    context_title = session[:context_title]

    if resource == "Listar certificados"
      redirect_to controller: "/certlist", user_id: user_id
      return
    end
    if resource == "Validar Certificado"
      redirect_to controller: "/tokencheck"
      return
    end 


    cert = Cert.where contex_id: context
    
    if cert.empty? #Caso não exista informação de certificado no banco
      if roles == "urn:lti:instrole:ims/lis/Administrator" #checar se regra é válida pra qualquer admin
        @course_id = context 
        @context_title = context_title
        @cert = Cert.new
        @verbose = "Criar"
        render new_cert_path
      else
        # TODO - Pagina avisando usuário que certificado não foi criado
        status_cert = "n encontrou"
      end
    else #Se existir informação do certificado no banco
      cert_context = Cert.where(contex_id: context).first

      # pegando horas do certificado e convertendo pra string
      #hours = Cert.where(:contex_id => context).pluck(:hours).first
      hours_string = cert_context.hours.to_s
      textprincipal = cert_context.description.to_s
      textmenu = cert_context.menu.to_s
      textname = cert_context.name.to_s

      #regra para substituir tags de texto
      if textprincipal =~ /\[nome\]/
        textprincipal.gsub!(/\[nome\]/, "<b style='text-decoration: underline'>"+fullname+"</b>")
      end

      if textprincipal =~ /\[curso\]/
        textprincipal.gsub!(/\[curso\]/, "<b style='text-decoration: underline'>"+context_title+"</b>")
      end

      if textprincipal =~ /\[horas\]/
        textprincipal.gsub!(/\[horas\]/, "<b style='text-decoration: underline'>"+hours_string+" Horas</b>")
      end

      # texto do usuario formatado
      @formated_name = textname
      @formated_description = textprincipal
      @formated_menu = textmenu

      # diretorio do arquivo PDF
      save_path = Rails.root.join('public',user_id+context+'.pdf')


      # Salvando no banco se não existir informação
      # Dessa forma é evitado que existam registros duplicados para o mesmo curso e
      # Permite que o usuário sobreescreva o arquivo por uma versão de Cert atualizada
      # Contudo um novo certificado é gerado sempre que a página é carregada
      # Talvez isso consuma recursos em demasia do servidor
      # Checar com o cliente a melhor abordagem posteriormente
      has_record = Emission.joins(:cert).where(:user_id => user_id).where(:certs => {:contex_id => context})
      if has_record.empty?
        #gerar token
        cert_token = SecureRandom.hex(6)

        emissao = Emission.create(user_id: user_id, cert_location: save_path, validation_token: cert_token)
        emissao.cert = cert_context
        emissao.save
      else
        cert_token = has_record.first.validation_token
      end

      # Usar token antigo se atualizar
      @token_show = cert_token

      # carregar imagens
      @front_image = wicked_active_storage_asset(cert_context.front_image)
      @back_image = wicked_active_storage_asset(cert_context.back_image)

      # Procura registro de emissão usuário atual
      # Gera String para criar PDF
      # Salva Arquivo PDF com active storage
      emission_record = Emission.joins(:cert).where(:user_id => user_id).where(:certs => {:contex_id => context})
      pdf = render_to_string pdf: "certificado", template: "application/cert_template.html.erb", encoding: "UTF-8", orientation: 'Landscape', margin:  {top: 2, bottom: 2,left: 2,right: 2}
      emission_record.first.certpdf.attach(io: StringIO.new(pdf), filename: user_id+context+".pdf", content_type: "application/pdf")
      @pdf_record = emission_record.first
      @cert_record = cert_context
      @roles = roles
  
    end
  end

  # Encontra o diretório da imagem para 
  # renderizar arquivos do Active Storage 
  # dentro do wiked_pdf
  def wicked_active_storage_asset(asset)
    return unless asset.respond_to?(:blob)
    save_path = Rails.root.join('tmp', asset.id.to_s)
    File.open(save_path, 'wb') do |file|
      file << asset.blob.download
    end
    save_path.to_s
  end

  # lTI XML Configuration
  # Used for easily installing your LTI into an LMS
  def lti_config
    render template: "application/lti_config.xml"
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/cert_template.html.erb
<div id="text-front" style="width: 100%; height: 975px; background: url('<%= @front_image %>') no-repeat; background-size: contain;">
    <h3 style="padding-top: 300px; font-size:35px; text-align: center; width: 70%; margin: 0 auto;"><%= sanitize @formated_name %></h3>
    <p style="width: 70%; text-align: center;margin: 0 auto;padding-top: 40px;font-size: 22px; line-height: 35px;">
    <%= sanitize @formated_description %>
    </p>
</div>
<div id="text-front" style="width: 100%; height: 975px; background: url('<%= @back_image %>') no-repeat; background-size: contain;">
    <p style="width: 85%; margin: 0 auto; text-align: left;padding-top: 150px;font-size: 22px; line-height: 35px;">
    <%= sanitize @formated_menu %>
    </p>
    <p style="font-size:22px; position: absolute; padding-left: 100px; padding-bottom: 100px; bottom:0;">Token do certificado:<b> <%= sanitize @token_show %></b></p>
</div>

app/views/application/index.html.erb
<h1>LTI Ruby on Rails Template</h1>

<h2>Configuration XML</h2>

<p>View the LTI configuration xml <a href="<%= lti_config_path %>" data-turbolinks="false">here</a></p>

<p>This configuration is used to install your LTI tool into an LSM.  This xml can be referenced by url or copied and pasted durring the install process.</p>

<h2>LTI Launch</h2>
<a name="" id="" class="btn btn-primary" href="#" role="button">asdasdasdasdasdasd</a>
<p>View the LTI Launch endpoint <a href="<%= lti_launch_path %>" data-turbolinks="false">here</a></p>

<p>Note, this url is typically sent a POST request with all sorts of LTI data.  If you access it directly, it'll display an error page indicating your request did not validate.</p>

<h3>Testing LTI Launch</h3>
<ol>
	<li>Visit the <a href="http://ltiapps.net/test/tc.php">IMS LTI Tool Consumer Emulator</a></li>
	<li>Set <b>Launch URL</b> to <span>"<%= lti_launch_url %>"</span></li>
	<li>Set <b>Consmer key</b> to the value defined in <span>"config/lti_settings.yml"</span></li>
	<li>Set <b>Shared secret</b> to the value defined in <span>"config/lti_settings.yml"</span></li>
</ol>

app/views/application/launch.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h2 class="pt-4">Certificado</h2>
			<p>Parabéns! Seu certificado está disponível! Você pode imprimi-lo ou fazer o download clicando nos botões abaixo. Caso você queria ver todos os seus certificados emitidos, clique em "meus certificados" no menu de usuário a esquerda.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="iframe-holder">
				<iframe src="<%= rails_blob_url(@pdf_record.certpdf) %>"> </iframe>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10"></div>
		<div class="col-md-2">
			<div class="form-group">
				<% if @roles == "urn:lti:instrole:ims/lis/Administrator" %>
				<%= link_to 'Atualizar', edit_cert_path(@cert_record.id), class:"btn btn-primary btn-lg btn-block mt-3" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/application/launch_created.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="mt-3">Certificado criado com sucesso!</h2>
            <p>Atualize a página se quiser ver as mudanças</p>
        </div>
    </div>
</div>

app/views/application/launch_error.html.erb
<h1 class="mt-3">Erro!</h1>
<p>Houve um erro de autorização. Atualize a página. Se o problema persistir, contate o suporte.</p>

app/views/application/lti_config.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<cartridge_basiclti_link xmlns="http://www.imsglobal.org/xsd/imslticc_v1p0"
    xmlns:blti = "http://www.imsglobal.org/xsd/imsbasiclti_v1p0"
    xmlns:lticm ="http://www.imsglobal.org/xsd/imslticm_v1p0"
    xmlns:lticp ="http://www.imsglobal.org/xsd/imslticp_v1p0"
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "http://www.imsglobal.org/xsd/imslticc_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticc_v1p0.xsd
    http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0.xsd
    http://www.imsglobal.org/xsd/imslticm_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticm_v1p0.xsd
    http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd">
    <blti:title>Certificado</blti:title>
    <blti:description>Esse aplicativo é utilizado para gerar certificados para os alunos, funciona dentro do contexto de cursos. Adicione-o como uma atividade usando a opção &quot;Ferramenta externa&quot;</blti:description>
    <blti:icon>https://certificadolti.herokuapp.com/public/certicon.png</blti:icon>
    <blti:launch_url>https://certificadolti.herokuapp.com/launch</blti:launch_url>
    <blti:extensions platform="canvas.instructure.com">
      <lticm:property name="tool_id">certificadolti</lticm:property>
      <lticm:property name="privacy_level">name_only</lticm:property>
      <lticm:property name="domain">certificadolti.herokuapp.com</lticm:property>
    </blti:extensions>
    <cartridge_bundle identifierref="BLTI001_Bundle"/>
    <cartridge_icon identifierref="BLTI001_Icon"/>
</cartridge_basiclti_link>